name: <%= name %>
version: 0.0.1
summary: Your ReactNative Ubuntu
description: This is <%= name %> description
confinement: devmode
apps:
  <%= name %>:
    command: bin/<%= name %> --local=./share/js/index.js --plugins-path=./plugins

parts:
  nodejs:
    plugin: nodejs

  react-native-app:
    plugin: copy
    source: ..
    files:
      bin/<%= name %>: bin/<%= name %>
      bin/ubuntu-server.js: bin/ubuntu-server.js
      share: share
      plugins: plugins

